CREATE DATABASE db_PICASO_OdhranH;
USE db_PICASO_OdhranH;

CREATE TABLE Client (
	ClientID INT AUTO_INCREMENT PRIMARY KEY,
	Forename VARCHAR(20) NOT NULL,
	Surname VARCHAR(20) NOT NULL,
	Address VARCHAR(50) NOT NULL,
	Phone VARCHAR(15) NOT NULL,
    SalesEmpID INT NOT NULL,
	ContractWon DATETIME NOT NULL,
    CONSTRAINT FOREIGN KEY (SalesEmpID) REFERENCES SalesEmployee(SalesEmpID)
);

# SQL for creating Delivery Employee table
CREATE TABLE DeliveryEmployee (
	DEmpID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	DEmpForename VARCHAR(20) NOT NULL,
	DEmpSurname VARCHAR(20) NOT NULL,
	DEMPBankNum VARCHAR(16) NOT NULL,
	NationalInsuranceNum VARCHAR(9) NOT NULL
);

CREATE TABLE Project (
	ProjectID INT NOT NULL AUTO_INCREMENT,
	ProjectName VARCHAR(50) NOT NULL,
	ProjectValue DECIMAL(9,2) NOT NULL,
	ClientID INT,
	TechLeadID INT NOT NULL,
    SalesEmpID INT,
	PRIMARY KEY (ProjectID),
	CONSTRAINT FOREIGN KEY (ClientID) REFERENCES `Client`(ClientID),
	CONSTRAINT FOREIGN KEY  (TechLeadID) REFERENCES DeliveryEmployee(DEmpID),
    CONSTRAINT FOREIGN KEY  (SalesEmpID) REFERENCES SalesEmployee(SalesEmpID)
);

CREATE TABLE Technologies (
	TechID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
	TechType VARCHAR(50) NOT NULL
);

CREATE TABLE Project_Tech (
	ProjectID INT NOT NULL,
	TechID INT NOT NULL,
	PRIMARY KEY (ProjectID,TechID),
	CONSTRAINT FOREIGN KEY (ProjectID) REFERENCES Project(ProjectID),
	CONSTRAINT FOREIGN KEY (TechID) REFERENCES Technologies(TechID)
);

CREATE TABLE SalesEmployee (
	SalesEmpID INT AUTO_INCREMENT PRIMARY KEY,
	Forename VARCHAR(20) NOT NULL,
	Surname VARCHAR(20) NOT NULL,
	Salary DECIMAL(9,2) NOT NULL,
	BAN VARCHAR(16) NOT NULL,
	NINumber VARCHAR(9) NOT NULL,
	ComRate DECIMAL(9,2) NOT NULL
);

CREATE TABLE Project_DeliveryEmployee(
	EmployeeID INT,
	ProjectID INT,
	StartDate DATE NOT NULL DEFAULT NOW(),
	EndDate DATETIME NULL,
	PRIMARY KEY(EmployeeID, ProjectID),
	FOREIGN KEY (EmployeeID) REFERENCES DeliveryEmployee(DEmpID),
	FOREIGN KEY (ProjectID) REFERENCES Project(ProjectID)
);
